import React, { useState, useEffect } from 'react';
import { 
  Activity, 
  TrendingUp, 
  ShieldAlert, 
  Target, 
  RefreshCw, 
  Clock, 
  ExternalLink,
  ChevronRight
} from 'lucide-react';

/**
 * App.jsx: The visual interface of your Stock Scanner.
 * It fetches data from 'signals.json' which is generated by your Python script.
 */
const App = () => {
  const [data, setData] = useState({ marketHealthy: true, signals: [], lastUpdated: "Never" });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  // Fetch the latest signals from the JSON file
  useEffect(() => {
    const fetchData = async () => {
      try {
        // We add a timestamp to the URL to prevent the browser from showing "old" cached data
        const response = await fetch(`./signals.json?t=${new Date().getTime()}`);
        if (response.ok) {
          const result = await response.json();
          setData(result);
          setError(false);
        } else {
          setError(true);
        }
      } catch (err) {
        console.error("Data not found. The scanner might still be running for the first time.");
        setError(true);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
    // Refresh the data every 5 minutes while the page is open
    const interval = setInterval(fetchData, 300000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans selection:bg-indigo-500/30">
      <div className="max-w-7xl mx-auto px-4 py-8 md:px-8">
        
        {/* TOP NAVIGATION / HEADER */}
        <header className="flex flex-col md:flex-row justify-between items-start md:items-center mb-10 gap-6">
          <div className="space-y-1">
            <div className="flex items-center gap-3">
              <div className="bg-indigo-600 p-2 rounded-xl shadow-lg shadow-indigo-500/20">
                <Activity className="text-white" size={24} />
              </div>
              <h1 className="text-2xl md:text-3xl font-black tracking-tight text-white uppercase italic">
                Swing<span className="text-indigo-500">Scanner</span>
              </h1>
            </div>
            <div className="flex items-center gap-2 text-slate-500 text-xs font-medium ml-1">
              <Clock size={12} />
              <span>Last Scan: {data.lastUpdated}</span>
            </div>
          </div>
          
          <div className="flex flex-wrap gap-3">
            {/* Market Health Status Badge */}
            <div className={`px-4 py-2 rounded-2xl border flex items-center gap-3 backdrop-blur-md ${data.marketHealthy ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : 'bg-rose-500/10 border-rose-500/20 text-rose-400'}`}>
              <div className={`w-2.5 h-2.5 rounded-full ${data.marketHealthy ? 'bg-emerald-500 animate-pulse' : 'bg-rose-500'}`} />
              <span className="font-bold text-xs uppercase tracking-widest">
                Market: {data.marketHealthy ? 'Healthy (Uptrend)' : 'Caution (Downtrend)'}
              </span>
            </div>
          </div>
        </header>

        {/* MAIN DASHBOARD CONTENT */}
        <div className="space-y-6">
          {loading ? (
            <div className="flex flex-col items-center justify-center p-32 space-y-4">
              <RefreshCw className="animate-spin text-indigo-500" size={48} />
              <p className="text-slate-500 font-medium animate-pulse">Analyzing Market Components...</p>
            </div>
          ) : error ? (
            <div className="bg-slate-900/50 border-2 border-dashed border-slate-800 rounded-3xl p-16 text-center">
              <div className="bg-rose-500/20 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <ShieldAlert className="text-rose-500" size={32} />
              </div>
              <h3 className="text-xl font-bold text-white mb-2">No Data Available</h3>
              <p className="text-slate-500 max-w-md mx-auto">
                The scanner hasn't generated the first report yet. This usually happens during the first deployment while the Python script is running.
              </p>
            </div>
          ) : data.signals.length > 0 ? (
            <div className="grid grid-cols-1 gap-4">
              {/* Opportunities Table */}
              <div className="bg-slate-900/40 border border-slate-800 rounded-3xl overflow-hidden backdrop-blur-xl shadow-2xl">
                <div className="px-6 py-4 border-b border-slate-800 flex justify-between items-center bg-slate-900/60">
                  <h3 className="font-bold text-slate-300 flex items-center gap-2">
                    <TrendingUp size={18} className="text-indigo-400" />
                    High Conviction Setups
                  </h3>
                  <span className="text-xs bg-indigo-500/10 text-indigo-400 px-2.5 py-1 rounded-lg font-bold">
                    {data.signals.length} Signals
                  </span>
                </div>
                
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                    <thead>
                      <tr className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em]">
                        <th className="px-6 py-5">Asset</th>
                        <th className="px-6 py-5">Current</th>
                        <th className="px-6 py-5">Entry (High)</th>
                        <th className="px-6 py-5">Target (10%)</th>
                        <th className="px-6 py-5">Protection</th>
                        <th className="px-6 py-5">Strength</th>
                        <th className="px-6 py-5"></th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800/50">
                      {data.signals.map((signal) => (
                        <tr key={signal.ticker} className="hover:bg-indigo-500/5 transition-all group">
                          <td className="px-6 py-6">
                            <div className="flex items-center gap-3">
                              <div className="w-10 h-10 rounded-xl bg-slate-800 flex items-center justify-center font-black text-indigo-400 border border-slate-700 group-hover:border-indigo-500/50 transition-colors">
                                {signal.ticker[0]}
                              </div>
                              <div className="flex flex-col">
                                <span className="text-xl font-black text-white group-hover:text-indigo-400 transition-colors">{signal.ticker}</span>
                                <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">{signal.type}</span>
                              </div>
                            </div>
                          </td>
                          <td className="px-6 py-6">
                            <span className="font-mono text-lg font-bold text-slate-200">${signal.currentPrice}</span>
                          </td>
                          <td className="px-6 py-6">
                            <div className="flex items-center gap-2 text-indigo-400 font-mono font-black text-lg">
                              <TrendingUp size={16} />
                              ${signal.buyAt}
                            </div>
                          </td>
                          <td className="px-6 py-6">
                            <div className="flex items-center gap-2 text-emerald-400 font-mono font-black text-lg">
                              <Target size={16} />
                              ${signal.goal}
                            </div>
                          </td>
                          <td className="px-6 py-6">
                            <div className="flex items-center gap-2 text-rose-500 font-mono font-black text-lg opacity-80 group-hover:opacity-100 transition-opacity">
                              <ShieldAlert size={16} />
                              ${signal.stopLoss}
                            </div>
                          </td>
                          <td className="px-6 py-6">
                            <div className="flex flex-col gap-1">
                              <span className={`text-[10px] font-black px-2 py-0.5 rounded-full w-fit ${signal.rsi > 60 ? 'bg-amber-500/10 text-amber-500' : 'bg-slate-800 text-slate-400'}`}>
                                RSI: {signal.rsi}
                              </span>
                              <div className="w-16 h-1 bg-slate-800 rounded-full overflow-hidden">
                                <div 
                                  className="h-full bg-indigo-500" 
                                  style={{ width: `${(signal.rsi / 100) * 100}%` }}
                                />
                              </div>
                            </div>
                          </td>
                          <td className="px-6 py-6 text-right">
                            <a 
                              href={`https://finance.yahoo.com/quote/${signal.ticker}`} 
                              target="_blank" 
                              rel="noreferrer"
                              className="p-2 text-slate-600 hover:text-white transition-colors inline-block"
                            >
                              <ExternalLink size={18} />
                            </a>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-slate-900/30 border-2 border-dashed border-slate-800 rounded-[2.5rem] p-24 text-center">
              <div className="bg-slate-800/50 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 text-slate-600">
                <RefreshCw size={40} />
              </div>
              <h3 className="text-2xl font-bold text-slate-400">Scanning 600+ Tickers...</h3>
              <p className="text-slate-600 mt-3 text-lg max-w-sm mx-auto">
                No setups currently match our High Conviction criteria. Checking again in 60 minutes.
              </p>
            </div>
          )}
        </div>
        
        <footer className="mt-16 pt-8 border-t border-slate-900 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-slate-600 text-[10px] uppercase font-bold tracking-widest">
            Automated Swing Analysis Engine • Alpha V4.0
          </p>
          <div className="flex gap-6 text-[10px] uppercase font-black text-slate-500 tracking-widest">
            <span className="hover:text-indigo-400 cursor-pointer transition-colors">Risk Disclaimer</span>
            <span className="hover:text-indigo-400 cursor-pointer transition-colors">API Status</span>
            <span className="text-indigo-500/50">Secure Mode Enabled</span>
          </div>
        </footer>
      </div>
    </div>
  );
};

export default App;